name: pixelsense
channels:
  - conda-forge
  - nvidia
  - pytorch-nightly
dependencies:
  - _openmp_mutex=4.5
  - aom=3.4.0
  - backports.zstd=1.3.0
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - charset-normalizer=3.4.4
  - cpython=3.10.19
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.1.80
  - cuda-runtime=12.4.1
  - cuda-version=13.1
  - ffmpeg=4.4.2
  - filelock=3.20.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.6
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jinja2=3.1.6
  - lame=3.100
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.16.0.49
  - libcurand=10.4.1.34
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.25
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=13.1.80
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpciaccess=0.18
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.20.0
  - libtiff=4.7.1
  - libunistring=0.9.10
  - libuuid=2.41.3
  - libva=2.23.0
  - libvpx=1.11.0
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.8.1
  - networkx=3.4.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openh264=2.3.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pillow=12.1.0
  - pip=25.3
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.6.0.dev20241112
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - svt-av1=1.2.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - torchaudio=2.5.0.dev20241113
  - torchvision=0.20.0.dev20241113
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.2
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.2
  - yaml=0.2.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - MarkupSafe==3.0.2
    - MouseInfo==0.1.3
    - PyAutoGUI==0.9.54
    - PyGetWindow==0.0.9
    - PyMsgBox==2.0.1
    - PyRect==0.2.0
    - PyScreeze==1.0.1
    - accelerate==1.12.0
    - annotated-doc==0.0.4
    - annotated-types==0.7.0
    - anyio==4.12.0
    - av==16.0.1
    - bitsandbytes==0.49.0
    - click==8.3.1
    - contourpy==1.3.2
    - cuda-bindings==12.9.4
    - cuda-pathfinder==1.2.2
    - cycler==0.12.1
    - decorator==5.2.1
    - decord==0.6.0
    - einops==0.8.1
    - exceptiongroup==1.3.1
    - fastapi==0.128.0
    - filelock==3.20.0
    - fonttools==4.61.1
    - fsspec==2025.12.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httptools==0.7.1
    - huggingface-hub==0.36.0
    - imageio-ffmpeg==0.6.0
    - kiwisolver==1.4.9
    - matplotlib==3.10.8
    - moviepy==2.2.1
    - mpmath==1.3.0
    - mss==10.1.0
    - networkx==3.4.2
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.28.9
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.4.5
    - nvidia-nvtx-cu12==12.8.90
    - opencv-python==4.12.0.88
    - packaging==25.0
    - pillow==11.3.0
    - proglog==0.1.12
    - psutil==7.2.1
    - pydantic==2.12.5
    - pydantic_core==2.41.5
    - pyparsing==3.3.1
    - pyperclip==1.11.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - python-multipart==0.0.21
    - python3-xlib==0.15
    - pytorch-triton==3.2.0+git4b3bb1f8
    - pytweening==1.2.0
    - qwen-vl-utils==0.0.14
    - regex==2025.11.3
    - safetensors==0.7.0
    - sentencepiece==0.2.1
    - six==1.17.0
    - starlette==0.50.0
    - sympy==1.14.0
    - timm==1.0.22
    - tokenizers==0.22.1
    - torch==2.11.0.dev20260104+cu128
    - torchaudio==2.10.0.dev20260104+cu128
    - torchvision==0.25.0.dev20260104+cu128
    - tqdm==4.67.1
    - transformers==4.57.3
    - triton==3.6.0+git9844da95
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - uvicorn==0.40.0
    - uvloop==0.22.1
    - watchfiles==1.1.1
    - websockets==16.0
    - yt-dlp==2025.12.8
